Base client-server
LostHikking/grandmastery pull request #24
Opened 2023-08-11 14:49 UTC by melniknow

2023-08-11 14:57 UTC, LostHikking commented on conversation/build.gradle.kts
> +    compileOnly("org.projectlombok:lombok:1.18.28")
Давай gradle плагином добавим и сразу везде?)

2023-08-11 15:00 UTC, LostHikking commented on client/src/main/java/io/deeplay/grandmastery/Client.java
> +  private static final Logger logger = LoggerFactory.getLogger(Client.class);
И если lombok, то давай и логгер им подключать.

2023-08-11 15:04 UTC, melniknow commented on client/src/main/java/io/deeplay/grandmastery/Client.java
> +  private static final Logger logger = LoggerFactory.getLogger(Client.class);
А так можно было?)

2023-08-11 15:49 UTC, LjeDmitr requested changes
Нужны хотя бы рабочие тесты для новых методов Boards

2023-08-11 15:49 UTC, LjeDmitr commented on game/src/main/java/io/deeplay/grandmastery/utils/Boards.java
> +      for (int j = 0; j < 8; j++) {
Я еще не на 100% уверен, но может лучше будет сделать просто for(i = 0; i < string.size(); i++), а чтобы получить row нужно i / 8 (целое число) и col это i % 8 (остаток от деления), так код сократиться и не будет двойных циклов.

2023-08-11 15:49 UTC, LjeDmitr commented on game/src/main/java/io/deeplay/grandmastery/utils/Boards.java
> +          board.setPiece(new Position(new Column(i), new Row(j)), piece);
У меня подозрения что здесь j это col, а i - row.

2023-08-11 15:49 UTC, LjeDmitr commented on game/src/main/java/io/deeplay/grandmastery/utils/Boards.java
> +  public static String getStringFromBoard(Board board) {
Так и не нашел тесты для getStringFromBoard и getBoardFromString (хотя я может слепой). Но если их нет, то лучше добавить, опасно это не тестировать

2023-08-11 16:52 UTC, LostHikking commented on build.gradle.kts
> +buildscript {
зачем так?

2023-08-11 16:52 UTC, LostHikking commented on build.gradle.kts
> +        implementation("io.freefair.lombok:io.freefair.lombok.gradle.plugin:8.1.0")
и это зачем?

2023-08-14 05:10 UTC, LjeDmitr approved these changes

2023-08-14 05:10 UTC, LjeDmitr commented on local/src/main/java/io/deeplay/grandmastery/TestGame.java
> +public class TestGame {
Тогда уж TestLocalGame)

2023-08-14 05:10 UTC, LjeDmitr commented on game/src/main/java/io/deeplay/grandmastery/utils/Boards.java
> +  public static boolean isEqualsBoards(Board first, Board second) {
Здесь Boards в название метода лишнее, и это будет выглядеть вот так Boards.isEqualsBoards. Типо тут и так понятно что мы борды сравниваем. Не то чтобы просто придирка, но у нас и так название большие у методов, у меня тоже, (надо будет вообще добавить таску для рефакторинга) и из-за этого строки в коде становятся больше и зачастую они съезжают вниз, что ухудшает читаемость кода. Поэтому почему не оставить просто Boards.equals)

2023-08-14 05:10 UTC, merged