Inship 37
LostHikking/grandmastery pull request #3
Opened 2023-07-28 09:50 UTC by melniknow

2023-07-28 14:28 UTC, LostHikking requested changes

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/core/GameHistory.java
> + * @author Sergei Melnikow
Давай без этого?)

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/core/GameHistory.java
> +            this.board = board; // TODO: Create with copy-constructor
Давай все комменты на русском будем писать?

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/domain/GameErrorCode.java
> +public enum GameErrorCode {
Можно сделать метод типа:
public GameException asException() {
return new GameException(this);
}
и потом красиво кидать исключения.

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/core/Position.java
> +    private static final List<Character> validCharacters = List.of('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h');
Константы в Java должны быть в SCREAMING_SNAKE_CASE

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/core/Position.java
> +        }
Не проще ли просто хранить готовую мапу?

2023-07-28 14:28 UTC, LostHikking commented on src/test/java/io/deeplay/service/LongAlgebraicNotationServiceTest.java
> +        assertEquals(FigureType.QUEEN, move.promotionPiece());
Давай тесты писать так, чтобы assert были только в конце и если их несколько использовать assertAll?

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/figures/Piece.java
> +        isMoved = moved;
Можно сделать проверку, что она с true не может меняться или лучше вообще чтобы метод ставил true не принимая аргументы

2023-07-28 14:28 UTC, LostHikking commented on src/main/java/io/deeplay/service/LongAlgebraicNotationService.java
> +public class LongAlgebraicNotationService {
У тебя по сути утилитный класс, содержащий только статичные функции, а ты его громко сервисом назвал) Есть формат файлов PGN, давай на него ориентироваться. На итоге нужен тест, чтобы PGN файлик из ресурсов полностью воспроизводил.

2023-07-28 14:30 UTC, LostHikking commented
И ещё PR надо нормально оформлять. Можно ссылку на саму задачу, нормально тему описать и тд.

2023-07-28 14:32 UTC, LostHikking commented on src/main/java/io/deeplay/core/Board.java
> +package io.deeplay.core;
И надо бы свой пакет создать, чтобы не пересекаться, мб у кого-нибудь будут идеи как проект можно красиво назвать, чтобы не писать 2023, стажировка, группа 1 и тд

2023-07-28 14:33 UTC, LostHikking commented on src/main/java/io/deeplay/core/Position.java
> +public record Position(int col, int row) {
Немного не то, что я имел в виду когда свои идеи говорил, но в целом можно и так. Если интересно разобраться как я хотел, можешь уточнить)

2023-07-29 08:11 UTC, LjeDmitr requested changes
В целом хотелось бы убрать GameListneres, чтобы в будущем не было мердж конфликтов, когда я его реализую, и написать новый интерфейс GameHistoryListeners, достаточно будет просто прикрутить его к классу GameHistory и методы переопределить. Я его потом сам создам в Game

2023-07-29 08:11 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/GameHistory.java
> +public class GameHistory implements GameListener {
Мы поменяли архитектуру, и теперь GameHistory должен реализовывать не GameListener, а GameHistoryListeners (см. архитектуру)

2023-07-29 08:11 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/GameListener.java
> +public interface GameListener {
Этот интерфейс устарел, его следует убрать). Я потом сам реализую новый GameListener, он по сути нужен только для класса Game

2023-07-29 08:11 UTC, LjeDmitr commented on src/test/java/io/deeplay/grandmastery/core/GameHistoryTest.java
> +    void setBoard() {
Возможно для читаемости кода, тесты стоит называть по типу testSetBoard, а не именами самих методов). Хотя возможно это уже моя придирка)

2023-07-31 08:26 UTC, LjeDmitr approved these changes

2023-07-31 08:32 UTC, motomoto8913 approved these changes

2023-07-31 08:51 UTC, LostHikking approved these changes

2023-07-31 08:54 UTC, merged