Реализация игровой доски HashBoard (INSHIP-50)
LostHikking/grandmastery pull request #4
Opened 2023-07-31 11:11 UTC by LjeDmitr

Описание:
Реализовал шахматную доску HashBoard. Создал вспомогательные классы King и Pawn для теста доски, написал тесты.

Ссылка на задачу:
[Link](https://jira.ourcode.ru/browse/INSHIP-50)

2023-07-31 11:24 UTC, melniknow requested changes

2023-07-31 11:24 UTC, melniknow commented on src/main/java/io/deeplay/grandmastery/core/Column.java
> +  @Override
В record уже переопределены equals & hashcode - это надо удалить

2023-07-31 11:24 UTC, melniknow commented on src/main/java/io/deeplay/grandmastery/core/Position.java
> +  @Override
Это тоже

2023-07-31 11:24 UTC, melniknow commented on src/main/java/io/deeplay/grandmastery/core/Row.java
> +  @Override
И это

2023-07-31 11:24 UTC, melniknow commented on src/test/java/io/deeplay/grandmastery/core/ChessBoardTest.java
> +    assertSame(pawn, retrievedPiece);
Нам здесь ссылки надо сравнить?

2023-07-31 11:29 UTC, LjeDmitr commented on src/test/java/io/deeplay/grandmastery/core/ChessBoardTest.java
> +    assertSame(pawn, retrievedPiece);
Если я правильно понял assertSame, то да. Тест смотрит что мы установили и достали один и тот же объект, а не два разных одного класса.

2023-07-31 11:37 UTC, LostHikking requested changes

2023-07-31 11:37 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/ChessBoard.java
> +public class ChessBoard extends Board {
Не очень нравится нейминг, у вас все борды шахматные, ChessBoard больше абстрактному классу подходит (но Board тоже вполне подходит абстрактному), а это что-то вроде HashBoard.

2023-07-31 11:37 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
Что этот метод делает/должен делать?

2023-07-31 11:37 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public abstract Piece getPiece(int col, int row);
Стоит убрать или сделать не абстрактным, чтобы дергался только метод выше.

2023-07-31 11:37 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public abstract Position getBlackKing();
getBlackKingPosition?

2023-07-31 11:40 UTC, motomoto8913 commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
Это мой, доску текущую будет показывать

2023-07-31 11:40 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
Показывать куда?

2023-07-31 11:48 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
Мысль понял, нужно переименовать его в showBoardToConsole?

2023-07-31 11:50 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
Вообще убрать, пускай какой-нибудь другой класс получает борду (какую угодно) и делает с ней что захочет.

2023-07-31 11:52 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public abstract Piece getPiece(int col, int row);
Уточню, если я хочу сохранить этот метод для удобства, например когда мы достаем фигуру можно либо создать объект Position, либо просто через два инта (что удобнее). То мне надо просто сделать его не абстрактным и написать реализацию в классе Board (то есть в этом же класс, что и был)

2023-07-31 11:55 UTC, motomoto8913 commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
> Вообще убрать, пускай какой-нибудь другой класс получает борду (какую угодно) и делает с ней что захочет.

Нормально тогда будет, если добавлю этот метод вывода доски в консоль в класс Game?

2023-07-31 11:58 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public void showBoard() {}
Я думаю лучше создать отдельный класс для вывода доски

2023-07-31 12:13 UTC, LostHikking commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public abstract Piece getPiece(int col, int row);
Напиши чтобы один метод дергался через другой, ты же можешь инты достать из Position?

2023-07-31 12:40 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/Board.java
> +  public abstract Piece getPiece(int col, int row);
Я наверное не так понял, это не для удобства реализации логики, а для пользователя грубо говоря. То есть у нас есть на выбор два варианта как достать фигуру из доски. Первый это создать класс Position и кинуть его в метод getPiece, получить фигур или в обход этого просто кинуть в метод getPiece два инта по x и y, и так же получить фигуру. У меня и так один метод вызывается в другом просто нужно ли эти два вариант, я думаю да, но в принципе можно убрать, особо трудностей не будет)

2023-08-01 08:37 UTC, motomoto8913 approved these changes

2023-08-01 08:38 UTC, melniknow approved these changes

2023-08-01 08:40 UTC, LostHikking approved these changes

2023-08-01 08:42 UTC, merged