feat:Add BoardRender, HumanPlayer, and Player classes with unittests
LostHikking/grandmastery pull request #6
Opened 2023-08-01 11:41 UTC by motomoto8913

Summary:
-Implement BoardRender, HumanPlayer, and Player classes 
-Write unit tests for BoardRender, HumanPlayer, and Player classes 
-Add minor functionality to HashBoard, King, Piece, and Pawn classes

2023-08-01 12:22 UTC, melniknow requested changes

2023-08-01 12:22 UTC, melniknow commented on src/main/java/io/deeplay/grandmastery/core/BoardRender.java
> + * ����� ����������� ����������� �����
С кодировкой траблы. Что-то кириллице плоховато)

2023-08-01 12:22 UTC, melniknow commented on src/main/java/io/deeplay/grandmastery/core/HumanPlayer.java
> +        while (true){
А зачем нам здесь while (true), если мы сразу же break делаем?

2023-08-01 12:22 UTC, smelnikowww commented on src/main/java/io/deeplay/grandmastery/core/HumanPlayer.java
> +        while (true){
Мы как бы дожидаемся валидного хода?

2023-08-01 12:22 UTC, smelnikowww commented on src/test/java/io/deeplay/grandmastery/core/PlayerTest.java
> +    void testSetInvalidMoveData_Format() {
Snakecase -> Camelcase

2023-08-01 12:22 UTC, smelnikowww commented on src/main/java/io/deeplay/grandmastery/core/BoardRender.java
> + * ����� ����������� ����������� �����
Причём везде

2023-08-01 12:36 UTC, motomoto8913 commented on src/main/java/io/deeplay/grandmastery/core/HumanPlayer.java
> +        while (true){
> Мы как бы дожидаемся валидного хода?

Ну тип, если ход корректный, то он записывается и выходим из цикла, иначе будет высвечиваться "Введите корректный ход:" - что-то типа того

2023-08-01 15:55 UTC, melniknow approved these changes, later dismissed

2023-08-01 16:23 UTC, LjeDmitr requested changes

2023-08-01 16:23 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/BoardRender.java
> +  public static void showHashBoard(OutputStream outputStream, HashBoard hashBoard) {
Я бы не передавал сюда HashBoard, он тебе тут не нужен, ты используешь только методы Board. Да и если представить что у нас есть помимо HashBoard, другие реализации по типо ArrayBoard и тд, то у тебя этот метод работать не будет.

2023-08-01 16:23 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/Player.java
> +    char startCol = moveData.charAt(0);
Мне кажется ненужная логика, у нас же есть в классе Column и Row, VALID_CHARACTERS, можно в них смотреть, валиден ли символ

2023-08-01 16:23 UTC, LjeDmitr commented on src/test/java/io/deeplay/grandmastery/core/PlayerTest.java
> +package io.deeplay.grandmastery.core;
Не совсем понял как ты тестишь Player ведь он абстрактный). Всм ты же тут тоже объект HumanPlayer создаешь и в тесте HumanPlayer тоже самое, мб в нем же все и тестировать а этот убрать, тем более что ты тут и там одни и те же методы тестируешь)

2023-08-01 16:23 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/HashBoard.java
> +  public Map<Position, Piece> getPieces() {
А это для чего?) Надо убрать доступ к мапе у нас через метод getPiece у Board

2023-08-01 16:23 UTC, LjeDmitr commented on src/main/java/io/deeplay/grandmastery/core/BoardRender.java
> +        Piece piece = hashBoard.getPieces().get(positionToCheck);
Вместо того чтобы обращаться напрямую в мапу, у класса Board есть метод getPiece, тоже самое по сути, ты также можешь кинуть в него объект Position или вообще два инта типа col и row

2023-08-02 04:31 UTC, motomoto8913 commented on src/test/java/io/deeplay/grandmastery/core/PlayerTest.java
> +package io.deeplay.grandmastery.core;
> Не совсем понял как ты тестишь Player ведь он абстрактный). Всм ты же тут тоже объект HumanPlayer создаешь и в тесте HumanPlayer тоже самое, мб в нем же все и тестировать а этот убрать, тем более что ты тут и там одни и те же методы тестируешь)

В плеере я тестировал только сам метод записи хода, а в дочернем - метод отвечающий за ввод. Он setMoveData внутри использует. Ну думаю да, перенесу всё в human

2023-08-02 09:16 UTC, LjeDmitr submitted a review, later dismissed

2023-08-02 09:18 UTC, LjeDmitr approved these changes

2023-08-02 09:18 UTC, smelnikowww approved these changes

2023-08-02 09:19 UTC, melniknow submitted a review, later dismissed

2023-08-02 09:20 UTC, LjeDmitr submitted a review, later dismissed

2023-08-02 09:27 UTC, LjeDmitr submitted a review, later dismissed

2023-08-02 09:28 UTC, LostHikking approved these changes, later dismissed

2023-08-02 09:29 UTC, melniknow submitted a review, later dismissed

2023-08-02 10:36 UTC, LjeDmitr approved these changes

2023-08-02 10:36 UTC, merged